webtalk_init -webtalk_dir E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_local/MIPS/mips_CF_Byte_addressable/mips_CF_Byte_addressable/mips_CF_Byte_addressable.sim/sim_1/behav/xsim/xsim.dir/r_mips_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb 19 17:28:13 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eb82ce1b-e696-4022-b9ac-9bc8cdfd19dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d13e5c06eb034fa395bc83a9b267ab81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "41" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "16" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "99 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "7 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "69" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "21" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.69_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "47676_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2122672215 -regid "" -xml E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_local/MIPS/mips_CF_Byte_addressable/mips_CF_Byte_addressable/mips_CF_Byte_addressable.sim/sim_1/behav/xsim/xsim.dir/r_mips_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_local/MIPS/mips_CF_Byte_addressable/mips_CF_Byte_addressable/mips_CF_Byte_addressable.sim/sim_1/behav/xsim/xsim.dir/r_mips_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_local/MIPS/mips_CF_Byte_addressable/mips_CF_Byte_addressable/mips_CF_Byte_addressable.sim/sim_1/behav/xsim/xsim.dir/r_mips_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
