webtalk_init -webtalk_dir E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_I_Arithmatic/mips_r_i/mips_r_i.sim/sim_1/behav/xsim/xsim.dir/sign_extend_16_to_32_bit_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Jan  4 22:54:09 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "eb82ce1b-e696-4022-b9ac-9bc8cdfd19dc" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f24278b4c7d34e779313a76c513ea94e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "80 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6412_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3310288224 -regid "" -xml E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_I_Arithmatic/mips_r_i/mips_r_i.sim/sim_1/behav/xsim/xsim.dir/sign_extend_16_to_32_bit_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_I_Arithmatic/mips_r_i/mips_r_i.sim/sim_1/behav/xsim/xsim.dir/sign_extend_16_to_32_bit_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/STUDY/Books/Electronica/microcontrollers/BITS/Onukr Mutulu Computer Architecture/MIPS_I_Arithmatic/mips_r_i/mips_r_i.sim/sim_1/behav/xsim/xsim.dir/sign_extend_16_to_32_bit_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
